on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - run: '[[ (( $(git show HEAD | grep "^-" | wc -l) -lt 10 )) ]]'
