on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run `./update.sh`
        run: ./update.sh
      - name: commit changes
        run: |
          git config --local user.name "Paul-Nicolas Madelaine"
          git config --local user.email "pnm@pnm.tf"
          git add .
          git commit -m "update games"
      - uses: ad-m/github-push-action@master
        with:
          branch: main
